[project]
name = "mathformer2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.3",
    "jinja2>=3.1.6",
    "numpy>=2.3.5",
    "torch>=2.9.1",
    "uvicorn>=0.38.0",
    "websockets>=15.0.1",
]
